/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema.admin;

import clases.conectar;
import clases.usuario;
import java.sql.Connection;

/**
 *
 * @author WILLIAN
 */
public class reporte_detallado extends javax.swing.JPanel {

    conectar cc_reporte_d =new conectar();
    Connection con_reporte_d;
    
    usuario user = new usuario();
    String fecha_actual;
    
    public reporte_detallado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        lista_detalle_general = new javax.swing.JTable();

        lista_detalle_general.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lista_detalle_general.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sala", "Nombre Pelicula", "Valor", "Espectadores", "Taquilla"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(lista_detalle_general);
        if (lista_detalle_general.getColumnModel().getColumnCount() > 0) {
            lista_detalle_general.getColumnModel().getColumn(0).setResizable(false);
            lista_detalle_general.getColumnModel().getColumn(1).setResizable(false);
            lista_detalle_general.getColumnModel().getColumn(2).setResizable(false);
            lista_detalle_general.getColumnModel().getColumn(3).setResizable(false);
            lista_detalle_general.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(703, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable lista_detalle_general;
    // End of variables declaration//GEN-END:variables
}
