/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema.admin;

import cinema.administrador;
import clases.conectar;
import clases.usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WILLIAN
 */
public class resoluciones extends javax.swing.JPanel {

    conectar cc_resolucion =new conectar();
    Connection con_resolucion;
    
    usuario user = new usuario();
    
    DefaultTableModel modelo_resoluciones;
    
    public resoluciones( usuario us) {
        user=us;
        
        initComponents();
        
        modelo_resoluciones =  (DefaultTableModel) lista_resoluciones.getModel();
        cargar();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numero = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        inicio = new javax.swing.JTextField();
        fin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_resoluciones = new javax.swing.JTable();
        agregar = new javax.swing.JButton();

        setBackground(new java.awt.Color(101, 149, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, -1));
        add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, -1));

        inicio.setEnabled(false);
        inicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inicioKeyTyped(evt);
            }
        });
        add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, -1));

        fin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                finKeyTyped(evt);
            }
        });
        add(fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, -1));

        jLabel1.setText("NUMERO DE RESOLUCION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 51, -1, -1));

        jLabel2.setText("FECHA DE RESOLUCION");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setText("CONSECUTIVO INICIAL");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jLabel4.setText("CONSECUTIVO FINAL");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RESOLUCIONES FACTURACION");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 398, -1));

        lista_resoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numero", "fecha", "inicio", "fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lista_resoluciones);
        if (lista_resoluciones.getColumnModel().getColumnCount() > 0) {
            lista_resoluciones.getColumnModel().getColumn(0).setResizable(false);
            lista_resoluciones.getColumnModel().getColumn(0).setPreferredWidth(140);
            lista_resoluciones.getColumnModel().getColumn(1).setResizable(false);
            lista_resoluciones.getColumnModel().getColumn(1).setPreferredWidth(90);
            lista_resoluciones.getColumnModel().getColumn(2).setResizable(false);
            lista_resoluciones.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 350, 218));

        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 257, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void cargar(){
        con_resolucion = cc_resolucion.conexion(user.get_ip());
        
        int a =modelo_resoluciones.getRowCount();
        for(int i=0; i<a;i++){
            modelo_resoluciones.removeRow(0);
        }
        

        try {
            Statement st = con_resolucion.createStatement();
            ResultSet result =st.executeQuery("SELECT * FROM resoluciones");

            while(result.next()){
                Object[] datosDeLaFila= new Object [4];
                
                datosDeLaFila[0]=result.getString(2);
                datosDeLaFila[1]=result.getString(3);
                datosDeLaFila[2]=result.getString(4);
                datosDeLaFila[3]=result.getString(5);
                
                modelo_resoluciones.addRow(datosDeLaFila);
                lista_resoluciones.setModel(modelo_resoluciones);
            }
            
            st = con_resolucion.createStatement();
            result =st.executeQuery("SELECT MAX(fin)+1 FROM resoluciones");

            result.next();
            
            inicio.setText(result.getInt(1)+"");
            
            con_resolucion.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"error 49:  "+ex);
            Logger.getLogger(administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if(Integer.parseInt(inicio.getText())>Integer.parseInt(fin.getText())){
            JOptionPane.showMessageDialog(null,"El valor final no puede ser menos a el valor inicial","error",JOptionPane.ERROR_MESSAGE);
        }
        else if(fecha.getDate() == null){
            JOptionPane.showMessageDialog(null,"debe seleccionar una fecha","error",JOptionPane.ERROR_MESSAGE);
        }
        else {
            String dia,mes,ano,fecha_res;
            dia= Integer.toString(fecha.getCalendar().get(Calendar.DAY_OF_MONTH));
            mes= Integer.toString(fecha.getCalendar().get(Calendar.MONTH)+1);
            ano= Integer.toString(fecha.getCalendar().get(Calendar.YEAR));
            fecha_res=ano+"-"+mes+"-"+dia;

            con_resolucion = cc_resolucion.conexion(user.get_ip());
            String sql="INSERT INTO resoluciones  (numero,fecha,inicio,fin) VALUES (?,?,?,?)";

            try {
                Statement st = con_resolucion.createStatement();
                ResultSet result =st.executeQuery("SELECT MAX(fin) FROM resoluciones");
                
                result.next();
                
                if(result.getInt(1)<Integer.parseInt(inicio.getText())){
                    
                                     
                    PreparedStatement pst= con_resolucion.prepareStatement(sql);
                    pst.setString(1,numero.getText());
                    pst.setString(2,fecha_res);
                    pst.setString(3,inicio.getText());
                    pst.setString(4,fin.getText());

                    pst.executeUpdate();

                    fecha.setDate(null);
                    numero.setText("");
                    inicio.setText("");
                    fin.setText("");
                    cargar();
                }
                else{
                    JOptionPane.showMessageDialog(null,"El rango coincide con otra resolucion","error",JOptionPane.ERROR_MESSAGE);
                }
                con_resolucion.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"error 50:  "+ex);
                Logger.getLogger(resoluciones.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void inicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inicioKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_inicioKeyTyped

    private void finKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_finKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_finKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JTextField fin;
    private javax.swing.JTextField inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lista_resoluciones;
    private javax.swing.JTextField numero;
    // End of variables declaration//GEN-END:variables
}
