/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import clases.conectar;
import clases.pelicula;
import clases.usuario;
import imprimir.imprimir_factura_gafas;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WILLIANC
 */
public class vender_gafas extends javax.swing.JDialog {

    conectar cc =new conectar();
    Connection con;
    String ip;
    DefaultTableModel modelo_reporte_gafas;
    ImageIcon icon = new ImageIcon("src/imagenes/gafas.png");
    int cantidad;
    boolean retornar;
    usuario user;
            
    public vender_gafas(java.awt.Frame parent, boolean modal, usuario us, boolean r) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        user=us;
        ip=user.get_ip();
        retornar=r;
        gafas_cantidad.requestFocus();
        
        if(retornar){
            vender.setText("AGREGAR");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gafas_cantidad = new javax.swing.JSpinner();
        vender = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setText("REPORTE VENTA GAFAS");

        gafas_cantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gafas_cantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));
        gafas_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gafas_cantidadKeyPressed(evt);
            }
        });

        vender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vender.setText("VENDER");
        vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderActionPerformed(evt);
            }
        });
        vender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                venderKeyPressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gafas.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(gafas_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vender, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(gafas_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vender, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderActionPerformed
        cantidad = Integer.parseInt(gafas_cantidad.getValue().toString());
        
        if(!retornar){
            vender();
        }
        dispose();
    }//GEN-LAST:event_venderActionPerformed

    private void gafas_cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gafas_cantidadKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER ){
            vender.requestFocus();
        }
    }//GEN-LAST:event_gafas_cantidadKeyPressed

    private void venderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_venderKeyPressed
        cantidad = Integer.parseInt(gafas_cantidad.getValue().toString());
        
        if(!retornar){
            vender();
        }
        dispose();
    }//GEN-LAST:event_venderKeyPressed
    
    public void vender(){
        try {
            con = cc.conexion(ip);

            Statement st;
            st = con.createStatement();
            ResultSet result =st.executeQuery("SELECT valor2d FROM precios where dia='8' ");
            result.next();

            int valor_unit = result.getInt(1);

            int confirmar = JOptionPane.showConfirmDialog(null," \n CANTIDAD   :   "+cantidad+" \n VALOR          :   $ "+(valor_unit*cantidad)+ "\n\n","Confirmar", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
            if (confirmar == JOptionPane.OK_OPTION){

                PreparedStatement pst = con.prepareStatement("INSERT INTO gafas (cantidad, valor, usuario_id) VALUES ( '"+cantidad+"', '"+(valor_unit*cantidad)+"', '"+user.get_id()+"')");
                pst.executeUpdate();

                imprimir_factura_gafas imprimir = new imprimir_factura_gafas(cantidad,(valor_unit*cantidad));
            }

            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"error 43  "+ex);

        }
    }
    
    public int get_cantidad(){
        return cantidad;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner gafas_cantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton vender;
    // End of variables declaration//GEN-END:variables
}
